### ISSUE TITLE
Documentação: Numeração errada na Especificação dos Casos de Uso

### ISSUE THREAD

**Issue by EijiDogen** [brunoorlandin/Source-Code-Inspection#31]
Na documentação Item 1.3, há dois subitens que estão enumerados 1.3.2
Favor, corrigir e colocar na ordem correta.

**Comment by brunoorlandin** [comment]
Ajustado o título duplicado 1.3.2 para 1.3.3
Link da página da wiki: https://github.com/brunoorlandin/Source-Code-Inspection/wiki/1.-Engenharia-de-Requisitos
